name: Desplegar a Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Desplegar en Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: haciendo-comunidad-db

      - name: Desplegar reglas de Firestore
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore:rules
        env:
          GCP_SA_KEY: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'

      - name: Desplegar reglas de Storage
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only storage
        env:
          GCP_SA_KEY: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
